#!/usr/bin/env bash
set -euo pipefail
set -x
dir="$(dirname "$(readlink -f "$0")")"

cd "$dir"

BUILD_PLATFORM="${BUILD_PLATFORM:-$(uname -s | tr '[:upper:]' '[:lower:]')}"
BUILD_PACKAGE="${BUILD_PACKAGE:-mlir-tools}"
BUILD_FOR_PYTHON="${BUILD_FOR_PYTHON:-cp310}"

CIBW_PLATFORM="linux"
CIBW_ARCHS="x86_64"
CIBW_MANYLINUX_IMAGE="manylinux_2_28"
CIBW_BUILD="$BUILD_FOR_PYTHON-manylinux*"

BUILD_CUDA_TOOLS="${BUILD_CUDA_TOOLS:-1}"
BUILD_VERBOSITY="${BUILD_VERBOSITY:-0}"
BUILD_LLVM_CLEAN_BUILD_DIR="${BUILD_LLVM_CLEAN_BUILD_DIR:-1}"
CIBW_DEBUG_KEEP_CONTAINER="${CIBW_DEBUG_KEEP_CONTAINER:-0}"
BUILD_CCACHE_DIR="${BUILD_CCACHE_DIR-}"
BUILD_PIP_CACHE_DIR="${BUILD_PIP_CACHE_DIR-}"

BUILD_LLVM_MLIR_BINDINGS=0
[ "$BUILD_PACKAGE" != "mlir-python-bindings" ] || BUILD_LLVM_MLIR_BINDINGS=1

CIBW_BEFORE_ALL="./install-build-tools.sh"
CIBW_BEFORE_BUILD="./install-llvm.sh && ./build-mlir.sh"
CIBW_BEFORE_TEST="./install-llvm.sh"
CIBW_TEST_COMMAND="{package}/test-installed.sh"

MACOSX_DEPLOYMENT_ARGS=""
CONTAINER_ENGINE_ARG=""
if [ "$BUILD_PLATFORM" = "linux" ]; then
    DOCKER_ARGS=""
    if [ -n "$BUILD_PIP_CACHE_DIR" ]; then
        DOCKER_PIP_CACHE_DIR="/pip_cache"
        DOCKER_ARGS="$DOCKER_ARGS -v'$BUILD_PIP_CACHE_DIR:$DOCKER_PIP_CACHE_DIR'"
        BUILD_PIP_CACHE_DIR="$DOCKER_PIP_CACHE_DIR"
    fi
    if [ -n "$BUILD_CCACHE_DIR" ]; then
        DOCKER_CCACHE_DIR="/ccache"
        DOCKER_ARGS="$DOCKER_ARGS -v'$BUILD_CCACHE_DIR:$DOCKER_CCACHE_DIR'"
        BUILD_CCACHE_DIR="$DOCKER_CCACHE_DIR"
    fi
    if [ -n "$BUILD_DNF_CACHE_DIR" ]; then
        DOCKER_DNF_CACHE_DIR="/var/cache/dnf"
        DOCKER_ARGS="$DOCKER_ARGS -v'$BUILD_DNF_CACHE_DIR:$DOCKER_DNF_CACHE_DIR'"
    fi
    CONTAINER_ENGINE_ARG="CIBW_CONTAINER_ENGINE=docker;create_args:$DOCKER_ARGS"
elif [ "$BUILD_PLATFORM" = "darwin" ]; then
    BUILD_CUDA_TOOLS=0
    CIBW_PLATFORM="macos"
    CIBW_ARCHS="arm64"
    CIBW_BUILD="$BUILD_FOR_PYTHON-macosx_arm64"
    CIBW_MANYLINUX_IMAGE="" 
    MACOSX_DEPLOYMENT_ARGS="MACOSX_DEPLOYMENT_TARGET=14.0" # supports macos14+
else
    echo "Error: Unknown BUILD_PLATFORM '$BUILD_PLATFORM'. Must be 'linux' or 'darwin'."
    exit 1
fi

ENV_VARS=(
    CIBW_PLATFORM="$CIBW_PLATFORM"
    CIBW_ARCHS="$CIBW_ARCHS"
    CIBW_BUILD="$CIBW_BUILD"
    CIBW_PROJECT_REQUIRES_PYTHON=">=3.10"
    CIBW_MANYLINUX_X86_64_IMAGE="$CIBW_MANYLINUX_IMAGE"
    CIBW_BEFORE_ALL="$CIBW_BEFORE_ALL"
    CIBW_BEFORE_BUILD="$CIBW_BEFORE_BUILD"
    CIBW_BEFORE_TEST="$CIBW_BEFORE_TEST"
    BUILD_LLVM_MLIR_BINDINGS="$BUILD_LLVM_MLIR_BINDINGS"
    CIBW_REPAIR_WHEEL_COMMAND_MACOS="pip install wheel && python mac-os-wheels-fixer.py --original {wheel} --output {dest_dir}"
    CIBW_REPAIR_WHEEL_COMMAND_LINUX="auditwheel repair --exclude 'libcuda.so.*'  --exclude 'libLLVM.so' -w {dest_dir} {wheel}" \
    CIBW_TEST_COMMAND="$CIBW_TEST_COMMAND"
    BUILD_PLATFORM="$BUILD_PLATFORM"
    PIP_CACHE_DIR="$BUILD_PIP_CACHE_DIR"
    CCACHE_DIR="$BUILD_CCACHE_DIR"
    BUILD_CUDA_TOOLS="$BUILD_CUDA_TOOLS"
    BUILD_LLVM_CLEAN_BUILD_DIR="$BUILD_LLVM_CLEAN_BUILD_DIR"
    CIBW_ENVIRONMENT_PASS="BUILD_LLVM_CLEAN_BUILD_DIR BUILD_PLATFORM PIP_CACHE_DIR CCACHE_DIR BUILD_CUDA_TOOLS BUILD_LLVM_MLIR_BINDINGS"
    CIBW_BUILD_VERBOSITY="$BUILD_VERBOSITY"
    CIBW_DEBUG_KEEP_CONTAINER="$CIBW_DEBUG_KEEP_CONTAINER"
)

[ -z "$CONTAINER_ENGINE_ARG" ] || ENV_VARS+=("$CONTAINER_ENGINE_ARG")
[ -z "$MACOSX_DEPLOYMENT_ARGS" ] || ENV_VARS+=("$MACOSX_DEPLOYMENT_ARGS")

env "${ENV_VARS[@]}" \
     "${CIBUILDWHEEL-cibuildwheel}" \
     "$BUILD_PACKAGE"

