#!/usr/bin/env bash
set -euo pipefail
set -x
dir="$(realpath -e "$(dirname "$0")")"

BUILD_LLVM_DEBUG_TARGET="${BUILD_LLVM_DEBUG_TARGET:-}"
BUILD_LLVM_CLEAN_BUILD_DIR="${BUILD_LLVM_CLEAN_BUILD_DIR:-1}"
LLVM_TARGETS_TO_BUILD="${LLVM_TARGETS_TO_BUILD-AArch64;ARM;X86}"

cd llvm-project

pip3 install -r mlir/python/requirements.txt

mkdir -p build
cmake \
    -DCMAKE_INSTALL_PREFIX="$dir"/install \
    -DLLVM_ENABLE_PROJECTS="mlir" \
    -DCMAKE_BUILD_TYPE=Release \
    -DLLVM_PARALLEL_LINK_JOBS=1 \
    -DCMAKE_PLATFORM_NO_VERSIONED_SONAME=ON \
    -DLLVM_TARGETS_TO_BUILD="$LLVM_TARGETS_TO_BUILD" \
    -DLLVM_INCLUDE_BENCHMARKS=OFF \
    -DLLVM_BUILD_BENCHMARKS=OFF \
    -DLLVM_INCLUDE_EXAMPLES=OFF \
    -DLLVM_BUILD_EXAMPLES=OFF \
    -DLLVM_INCLUDE_TESTS=OFF \
    -DLLVM_BUILD_TESTS=OFF \
    -DLLVM_INCLUDE_DOCS=OFF \
    -DLLVM_BUILD_DOCS=OFF \
    -DLLVM_BUILD_LLVM_DYLIB=ON \
    -DLLVM_LINK_LLVM_DYLIB=ON \
    -DLLVM_INCLUDE_TOOLS=ON \
    -DLLVM_BUILD_TOOLS=OFF \
    -DLLVM_INCLUDE_UTILS=OFF \
    -DLLVM_BUILD_UTILS=OFF \
    -DLLVM_TOOL_LLVM_DRIVER_BUILD=OFF \
    -DLLVM_TOOL_LTO_BUILD=OFF \
    -DLLVM_TOOL_GOLD_BUILD=OFF \
    -DLLVM_TOOL_LLVM_AR_BUILD=OFF \
    -DLLVM_TOOL_LLVM_AR_BUILD=OFF \
    -DLLVM_TOOL_LLVM_LTO_BUILD=OFF \
    -DLLVM_TOOL_LLVM_PROFDATA_BUILD=OFF \
    -DLLVM_TOOL_LLD_BUILD=OFF \
    -DLLVM_TOOL_CLANG_BUILD=OFF \
    -DLLVM_TOOL_FLANG_BUILD=OFF \
    -DLLVM_TOOL_LLDB_BUILD=OFF \
    -DLLVM_TOOL_BOLT_BUILD=OFF \
    -DLLVM_TOOL_POLLY_BUILD=OFF \
    -DLLVM_TOOL_LIBCLC_BUILD=OFF \
    -DLLVM_TOOL_LLVM_CONFIG_BUILD=ON \
    -DLLVM_TOOL_MLIR_BUILD=ON \
    -DMLIR_INCLUDE_INTEGRATION_TESTS=OFF \
    -DMLIR_INCLUDE_TESTS=OFF \
    -DMLIR_BUILD_MLIR_C_DYLIB=ON \
    -DMLIR_ENABLE_BINDINGS_PYTHON=ON \
    -DMLIR_ENABLE_EXECUTION_ENGINE=ON \
    -DMLIR_ENABLE_SPIRV_CPU_RUNNER=ON \
    -DLLVM_CCACHE_BUILD=ON \
    -DCMAKE_C_COMPILER_LAUNCHER=ccache \
    -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
    -G Ninja \
    -B build llvm

if [ -z "$BUILD_LLVM_DEBUG_TARGET" ]; then
    ninja -C build
    ninja -C build install
else
    ninja -C build $BUILD_LLVM_DEBUG_TARGET
fi

[ "$BUILD_LLVM_CLEAN_BUILD_DIR" != 1 ] || rm -rf build

#    -DCMAKE_VISIBILITY_INLINES_HIDDEN=ON \
#    -DCMAKE_C_VISIBILITY_PRESET=hidden \
#    -DCMAKE_CXX_VISIBILITY_PRESET=hidden \
